// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DrinkLink.Data.DrinkLink
{
    public partial class DrinkLinkProductCategory
    {
        public string DlProductCategoryId { get; set; }
        public string DlProductCategoryName { get; set; }
    }
}