// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DrinkLink.Data.DrinkLink
{
    public partial class DrinkLinkOrderCurrentProduct
    {
        public string DlOrderCurrentProductId { get; set; }
        public string DlOrderCurrentProduct { get; set; }

        public string DlOrderCurrentProductQuantity { get; set; }
        public string DlOrderCurrentQuantity { get; set; }



        public DateTime DlOrderDate { get; set; }
        public string DlOrderStatusStatus { get; set; }

        public string DlOrderCurrentOrderId { get; set; }

    }
 
}

