// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DrinkLink.Data.DrinkLink
{
    public partial class DrinkLinkProductQuantity
    {
        public string DlProductQuantityProductId { get; set; }
        public int DlProductQuantityUnits { get; set; }
    }
}