// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DrinkLink.Data.DrinkLink
{
    public partial class DrinkLinkProducts
    {
        public string DlProductId { get; set; }
      
        public string DlProductOwnership { get; set; }
        [RegularExpression(@"^[a-zA-Z0-9""'\s-]*$", ErrorMessage = "Invalid Characters Entered")]
        [Required(ErrorMessage = "This field is required")]
        [StringLength(30)]
        public string DlProductName { get; set; }
        [RegularExpression(@"^[a-zA-Z0-9""'\s-]*$", ErrorMessage = "Invalid Characters Entered")]
        [Required(ErrorMessage = "This field is required")]
        [StringLength(100)]
        public string DlProductDescription { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string DlProductAvailableQUantity { get; set; }
    }
}