// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DrinkLink.Data.DrinkLink
{
    public partial class DrinkLinkOrderCurrentCustomer
    {

        public string DlOrderId { get; set; }
        public string DlOrderCustomerNames { get; set; }

        public string DlOrderCustomerAddress { get; set; }

        public DateTime DlOrderDate { get; set; }

    }
}

