// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DrinkLink.Data.DrinkLink
{
    public partial class DrinkLinkOrder
    {
        public string DlOrderId { get; set; }
        public string DlOrderProductId { get; set; }
        public string DlOrderCustomerId { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "Invalid Characters Entered")]
        public string DlOrderQuantity { get; set; }
        public DateTime? DlOrderDate { get; set; }

        public string DlOrderParentOrderId { get; set; }
    }
}