// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace DrinkLink.Data.DrinkLink
{
    public partial class DrinkLinkContacts
    {
        public string DlContactId { get; set; }
        public string DlContactOwnership { get; set; }
        public string DlContactName { get; set; }
        public string DlContactAddressLine1 { get; set; }
        public string DlContactAddressLine2 { get; set; }
        public string DlContactAddressLine3 { get; set; }
        public string DlContactAddressPostCode { get; set; }
       
        public int DlContactPhoneNumber { get; set; }

        public string DlContactEmail { get; set; }

        public bool DlContactsIsConfirmed { get; set; }

        

    }
}